# Generated by Django 4.2 on 2024-05-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Get_Quote_Page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getquote',
            old_name='eamil',
            new_name='email',
        ),
    ]
