# Generated by Django 4.2 on 2024-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Why_Selecting_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('happy_Clients', models.IntegerField(max_length=5)),
                ('happy_Clients_Desc', models.TextField(max_length=600)),
                ('personal_Consultants', models.IntegerField(max_length=5)),
                ('personal_Consultants_Desc', models.TextField(max_length=600)),
                ('custom_Services', models.IntegerField(max_length=5)),
                ('custom_Services_Desc', models.TextField(max_length=600)),
                ('years_of_Experience', models.IntegerField(max_length=5)),
                ('years_of_Experience_Desc', models.TextField(max_length=600)),
            ],
        ),
    ]
