# Generated by Django 4.2 on 2024-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0005_alter_why_selecting_us_custom_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Level_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='C_Level_Person/')),
                ('message', models.TextField()),
            ],
        ),
    ]
