# Generated by Django 4.2 on 2024-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0006_c_level_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='SI_ID',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
