# Generated by Django 4.2 on 2024-07-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0009_alter_teammember_si_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='SI_ID',
            new_name='SI',
        ),
    ]
