# Generated by Django 4.2 on 2024-07-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0012_teammember_is_draft_alter_teammember_si'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
