# Generated by Django 4.2 on 2024-07-02 05:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0014_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_selecting_us',
            name='we_Do',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
